version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"

  jobs:
    post_create_environment:
      # Install Poetry
      - pip install poetry

    post_install:
      # Install your dependencies using Poetry, including dev group
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH poetry install --with dev

mkdocs:
  configuration: mkdocs.yml
