site_name: NFL API Client
site_url: https://nfl-api-client.readthedocs.io/


repo_url: https://github.com/haydenfd/nfl_api_client
repo_name: haydenfd/nfl_api_client

nav:
  - Home: index.md
  - Guide: 
    - Overview: guide.md
    - Data Access: data_access.md
    - HTTP Request Configuration: request_config.md
  - Reference:
    - Overview: reference.md
    - Endpoints:
        - Player Career Statistics: player_career_stats.md
        - Team Roster: team_roster.md
        - Team Depth Chart: team_depth_chart.md
        - Team Schedule: team_schedule.md
        # - Season Standings (Basic): season_standings.md
        - Season Statistics Leaders: stats_leaders.md
        - Game Officials: game_officials.md
        - Game Boxscore Statistics (Team): game_team_stats.md
        # - Season Standings (Expanded): season_standings_expanded.md
        # - Season Standings (Playoff Picture): season_standings_playoffs.md
    - Parameters: parameters.md
  - CHANGELOG: CHANGELOG.md

plugins:
  - search
  - mkdocstrings:
      default_handler: python
  - mermaid2

watch:
  - src

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  

# Theme config 

theme:
  name: material
  icon:
    logo: material/football
    favicon: material/football  
  features:
    - navigation.tabs
    - content.code.copy
  palette:
    - scheme: slate
      primary: indigo
      accent: lime
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

    - scheme: default
      primary: deep orange
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  font: 
    text: Inter
    code: IBM Plex

extra_css:
  - custom-styles.css
