import requests
import os


project_root = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
relative_path = os.path.relpath(__file__, start=project_root)

def fetch_active_players():
    url = "https://sports.core.api.espn.com/v3/sports/football/nfl/athletes?limit=20000"
    response = requests.get(url)
    data = response.json()

    players = []
    for item in data.get("items", []):
        if item.get("active"):
            players.append([
                int(item["id"]),
                item.get("fullName", ""),
                item.get("firstName", ""),
                item.get("lastName", "")
            ])
    return players

def save_to_data_py(players):
    output_path = os.path.join(os.path.dirname(__file__), "../lib/data.py")
    os.makedirs(os.path.dirname(output_path), exist_ok=True)

    with open(output_path, "w") as f:
        f.write(f"# DO NOT MODIFY: This file has been auto-generated by {relative_path}.\n\n")
        f.write(f"players = {repr(players)}\n")

if __name__ == "__main__":
    active_players = fetch_active_players()
    save_to_data_py(active_players)
